mkdir build
cd build
mkdir E:\fltk
cmake.exe -D CMAKE_BUILD_TYPE=Release -D OPTION_USE_SYSTEM_LIBJPEG=OFF -D OPTION_USE_SYSTEM_LIBPNG=OFF -D OPTION_USE_SYSTEM_ZLIB=OFF -D OPTION_BUILD_SHARED_LIBS=ON -D CMAKE_INSTALL_PREFIX=E:\fltk -G "MinGW Makefiles" ..
make.exe
